/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Client;

/**
 *
 * @author Momar Ndaw THIAM
 */
public class Empruntform extends javax.swing.JFrame {

    /**
     * Creates new form Empruntform
     */
    public Empruntform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateretour_txt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prenom_txt = new javax.swing.JTextField();
        nom_txt = new javax.swing.JTextField();
        telephone_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        livreemprunt_txt = new javax.swing.JTextField();
        dateemprunt_txt = new com.toedter.calendar.JDateChooser();
        dateretourprevu_txt = new com.toedter.calendar.JDateChooser();
        dateretoureffectif_txt = new com.toedter.calendar.JDateChooser();
        valider_txt = new javax.swing.JButton();
        retour_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateretour_txt.setBackground(new java.awt.Color(255, 255, 255,80
        ));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Gestion Emprunt");

        jLabel3.setText("Prenom");

        jLabel4.setText("nom");

        jLabel5.setText("telephone");

        jLabel6.setText("email");

        jLabel7.setText("livre emprunter");

        jLabel8.setText("Date emprunt");

        jLabel9.setText("Date de retour prevu");

        jLabel10.setText("Date retour effectif");

        valider_txt.setText("valider");
        valider_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_txtActionPerformed(evt);
            }
        });

        retour_btn.setText("retour");
        retour_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dateretour_txtLayout = new javax.swing.GroupLayout(dateretour_txt);
        dateretour_txt.setLayout(dateretour_txtLayout);
        dateretour_txtLayout.setHorizontalGroup(
            dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateretour_txtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(dateretour_txtLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dateretour_txtLayout.createSequentialGroup()
                        .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(65, 65, 65)
                        .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telephone_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(nom_txt)
                            .addComponent(prenom_txt)
                            .addComponent(email_txt)
                            .addComponent(livreemprunt_txt))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateretour_txtLayout.createSequentialGroup()
                        .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dateretour_txtLayout.createSequentialGroup()
                                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(36, 36, 36)
                                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateemprunt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateretoureffectif_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dateretour_txtLayout.createSequentialGroup()
                                        .addComponent(dateretourprevu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                        .addComponent(retour_btn))))
                            .addGroup(dateretour_txtLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valider_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))))
        );
        dateretour_txtLayout.setVerticalGroup(
            dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateretour_txtLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prenom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telephone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valider_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(livreemprunt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dateemprunt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dateretour_txtLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addGroup(dateretour_txtLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retour_btn)
                            .addComponent(dateretourprevu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(dateretour_txtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(dateretoureffectif_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(dateretour_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 490, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Momar Ndaw THIAM\\Downloads\\abcd.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retour_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_btnActionPerformed
Interfacebiblio it = new Interfacebiblio();
it.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_retour_btnActionPerformed

    private void valider_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_txtActionPerformed
if (!testFied( prenom_txt.getText(), nom_txt.getText(),telephone_txt.getText(),email_txt.getText(),livreemprunt_txt.getText(),dateemprunt_txt.getDateFormatString(),dateretourprevu_txt.getDateFormatString(),dateretoureffectif_txt.getDateFormatString())){
    JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs");
                     return;
                 }
                 // pour recuperer les valeurs des champs du formulaire
         String email = email_txt.getText();
        String nom = nom_txt.getText();
        String prenom = prenom_txt.getText();
        String livreemprunt = livreemprunt_txt.getText();
        String telephone= telephone_txt.getText();
       String dateemprunt =dateemprunt_txt.getDateFormatString();
       String dateretourprevu =dateretourprevu_txt.getDateFormatString();
       String dateretoureffectif =dateretoureffectif_txt.getDateFormatString();
      SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
       //String dateInscriptionTexte = format.format(dateInscription);
       
                

                 if (nom.length() < 2) {
                     JOptionPane.showMessageDialog(this, "Le nom doit avoir au minimum 2 lettres !", "Input Error", JOptionPane.ERROR_MESSAGE);
                     return;
                 }
                 if (prenom.length() < 2) {
                     JOptionPane.showMessageDialog(this, "Le prenom doit avoir au minimum 2 lettres", "Input Error", JOptionPane.ERROR_MESSAGE);
                     return;
                 }

                 if (telephone.length() < 9 || !(telephone.startsWith("77") || telephone.startsWith("78") || telephone.startsWith("76") || telephone.startsWith("75")
                         || telephone.startsWith("70"))) {
                     JOptionPane.showMessageDialog(this, "Le numero doit avoir 9 chiffres au moins ! et commencer par 77,78,75,70", "Input Error", JOptionPane.ERROR_MESSAGE);
                     return;
                 }
                  if (verifieEmail(email)) {
            JOptionPane.showMessageDialog(this, "L'email existe déjà !");
            return;    
        }

    try {
        if (verifieTelExiste(telephone)) {
            JOptionPane.showMessageDialog(this, "Le Numero  existe déjà !");
            return;    
        }
    } catch (Exception ex) {
        Logger.getLogger(AddClient.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
        
        
        
        
    }//GEN-LAST:event_valider_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empruntform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empruntform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empruntform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empruntform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empruntform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateemprunt_txt;
    private javax.swing.JPanel dateretour_txt;
    private com.toedter.calendar.JDateChooser dateretoureffectif_txt;
    private com.toedter.calendar.JDateChooser dateretourprevu_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField livreemprunt_txt;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JTextField prenom_txt;
    private javax.swing.JButton retour_btn;
    private javax.swing.JTextField telephone_txt;
    private javax.swing.JButton valider_txt;
    // End of variables declaration//GEN-END:variables
}
  private boolean testFied (String prenom, String nom, String telephone, String email, String dateemrunt, String dateretourprevu, String dateretoureffectif, String livreemprunt) {
    return !(prenom.trim().isEmpty()
            || nom.trim().isEmpty()
            || telephone.trim().isEmpty()
             || livreemprunt.trim().isEmpty()
            || email.trim().isEmpty()); 
            || email.trim().isEmpty()); 
}

           
   

//    private boolean verifieEmail(String email) {
//        List<Emprunt> emprunts = IEmprunt.AllEmprunt();
//    for (Emprunt e : emprunts) {
//        if (c.getEmail().equals(email)) {
//            return true;
//        }
//    }
//    return false;
//    }
//    
//
//    private boolean verifieTelExiste(String telephone) {
//         List<Client> clients = iClient.AllClients();
//    for (Client c : clients) {
//        if (c.getTelephone().equals(telephone)) {
//            return true;
//        }
//    }
//    return false;
//    }
//}
